### ISSUE TITLE
Relative setting or normalisation of thresholds

### ISSUE THREAD

**Issue by LandUseChange** [CRAFTY-ABM/CRAFTY_CoBRA_Impressions_KIT#1]
Every time a threshold is used, it's converted to a proportion of the mean benefit value across the current population of agents.
Ideally the current mean value.
 
SD gap normalisation
SD gap relative to the current demand
E.g. Gap_i = (S_i - D_i)/D_i

In competition.xml, one can specify normaliseCellResidual and normaliseCellSupply
    <competition class="org.volante.abm.example.NormalisedCurveCompetitivenessModel" removeNegative="true" normaliseCellResidual="true" normaliseCellSupply="true">
by default both are `true' (means we normalise both).

They trigger normalisation is implemented in
org.volante.abm.agent.NormalisedCurveCompetitivenessModel.java
‌
and done for each cell.
 
DefaultLandUseAgent.considerGivingUp() and DefaultLandUseAgent.considerGivingUp.ProductionModel()

**Comment by alanbseo** [comment]
Moved to https://github.com/CRAFTY-ABM/CRAFTY_CoBRA/issues/2
