### ISSUE TITLE
GUI improvements

### ISSUE THREAD

**Issue by LandUseChange** [CRAFTY-ABM/CRAFTY_CoBRA_Impressions_KIT#3]
Here to list up desired improvements of the current GUI (model display and control window)
 
The control window does not close when the button is pressed. It is due to a NullPointerException occurred in the finalActions() method. Java AWT thread is independent from the main thread, thus the object not accessible from the window thread. To fix it, it needs a handle to the main thread (to close file streams etc.).

**Comment by alanbseo** [comment]
Moved to https://github.com/CRAFTY-ABM/CRAFTY_CoBRA/issues/3
